name: Simple-CI

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: windows-2019
    environment: env-1
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Run a simple command
        run: |
          date
      - name: debug
        run: |
          echo ${{vars}}
      - name: echo environment name
        run: |
          echo ${{vars.NAME}}