name: Simple-CI

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: windows-2019
    environment: env-1
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - shell: bash
        run: |
          ${{vars.NAME}} > env.txt
      - name: Create Environment artifact
        uses: actions/upload-artifact@v4
        with:
          name: env_manifest
          path: env.txt